services:
    # nopcommerce_web:
    #     build: .
    #     container_name: nopcommerce
    #     ports:
    #         - "80:80"
    #     depends_on:
    #         - data
    nop_data:
        image: "postgres:latest"
        container_name: nop-postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        healthcheck:
          test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
          interval: 5s
          timeout: 5s
          retries: 5
        volumes:
          - nop-db:/var/lib/postgresql
          - ./settings/init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql:ro,z


    pgadmin:
        image: dpage/pgadmin4
        container_name: nop-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@ecomzen.ca
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        restart: unless-stopped
        depends_on:
            nop_data:
                condition: service_healthy
        ports:
           - "5050:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
            - ./backups:/var/lib/pgadmin/storage
            - ./settings/servers.json:/pgadmin4/servers.json
 

volumes:
    nop-db:
    pgadmin-data:           